### ISSUE TITLE
The name 'Blackjack' is very ungoogleable

### ISSUE THREAD

**Issue by FeldrinH** [setzer22/blackjack#16]
It's not really an issue with the software itself, but if this project wants to improve it's visibility and discoverability I think it is a relevant issue to consider.

Searching by the name 'Blackjack', it is very difficult to find this project in Google and other search engines.
Searching just 'blackjack' gets results about the card game blackjack. Searching 'blackjack modelling software' finds software to model and simulate the card game blackjack. Searching 'rust blackjack' finds a number of rust crates named or related to blackjack the card game but (right now) suprisingly not this project, at least not on the first page on Google.

**Comment by setzer22** [comment]
This is a very young and relatively unknown project (even though I'm truly grateful for the nice response I've seen so far! :tada:), so I'm not surprised that it's very difficult to find it on search engines That would probably be the case even if it had the most unique name I could come up with :thinking:

But I see your point, I also made the exercise to search for blackjack and it's a bit frustrating not being able to find *my own* project, even when considering Google has all this data about me!

I'd be inclined to wait a bit until I get more content about this project out there, and if the "googleability" situation doesn't improve then I can start seriously considering a rename. Visibility is not a huge priority for me right now, because this project is at such an early stage that even if people knew about it there's very little useful work they could get done with it. First we need a few more features :)

I'll keep this issue open, so if anyone reading this wants to suggest an alternative name I'm all ears!

**Comment by setzer22** [comment]
I've been pondering about this over the past few months. I just checked today, and the situation is what I'd call *good enough* for blackjack's current state. If you look for just "blackjack" you're not likely to find this project, but looking for "blackjack procedural", "blackjack 3d modelling" or "blackjack rust" seems to be enough to put this project among the top search results. I made this experiment using anonymized searches via startpage and duckduckgo, as well as Google on a "clean" session (as clean as I could manage to make it).

Taking into account that I've so far put zero effort on SEO, I'm inclined to keep the name. I like it a lot, after all :smile:
