### ISSUE TITLE
Build on Windows failed.

### ISSUE THREAD

**Issue by zeroxer** [setzer22/blackjack#54]
Is there any windows building test?

**Comment by setzer22** [comment]
Not currently, but I am planning to look into that by setting up CI releases for the major platforms.

What's the error you're getting, in the meantime?

**Comment by DamenH** [comment]
I am on Windows 11. I get the following error:

```
error: failed to run custom build command for `gdnative-sys v0.10.1`

Caused by:
  process didn't exit successfully: `C:\Users\damen\Documents\Projects\blackjack\target\debug\build\gdnative-sys-c05f9e568170cd89\build-script-build` (exit code: 101)
  --- stderr
  thread 'main' panicked at 'Unable to find libclang: "couldn't find any valid shared libraries matching: ['clang.dll', 'libclang.dll'], set the `LIBCLANG_PATH` environment variable to a path where one of these files can be found (invalid: [])"', C:\Users\damen\.cargo\registry\src\github.com-1ecc6299db9ec823\bindgen-0.60.1\src/lib.rs:2172:31
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

Thanks

**Comment by setzer22** [comment]
Ah, that's unfortunate :thinking:  This seems to be happening when building the godot integration (@Bromeon may want to check this error message). 

If you're not planning on using the godot integration, you should be able to get this working by building the `blackjack_ui` crate directly. Simply run:
```bash
cargo run --bin blackjack_ui
```

**Comment by setzer22** [comment]
Ok, so it seems the issue is simply that godot-rust wants LLVM to be installed in the system where it's built. This is explained in their user guide: https://godot-rust.github.io/book/getting-started/setup.html#llvm

Because not all blackjack users will care about Godot, it makes sense to not build the crate unless you need it, so the advice to only compile `blackjack_ui` is the right answer.

@DamenH, @zeroxer: Could you confirm after building with `cargo run --bin blackjack_ui` the error is gone?

**Comment by DamenH** [comment]
Awesome. It is now building with no issues. It doesn't seem like there is much to do, but perhaps that's intentional?

![image](https://user-images.githubusercontent.com/8838117/198893453-a5ebb212-97bb-4a03-bae6-190a986f0a68.png)

I will try to get this working with LLVM and Godot soon. Thank you for the help. Keep up the great work.

**Comment by setzer22** [comment]
Amazing! Glad I was able to help :)
