### ISSUE TITLE
Small interface on MacBook Pro

### ISSUE THREAD

**Issue by Kerollmops** [setzer22/blackjack#6]
I am on a MacBook Pro 13.3' which has a high resolution i.e. 2560×1600. I read [in the documentation of winit](https://docs.rs/winit/latest/winit/dpi/index.html) that you should decorrelate window size and resolution.

**Comment by setzer22** [comment]
Thanks for reporting :+1:  That's strange, though. I'm using the hidpi scale value as reported by winit and handing that over to egui, so I don't see how that could be an issue.

I just pushed 3c08b52ab5, which adds a "Diagnostics" window under "Help" (top menu bar). If you click that, you should be able to see the dpi value. For your screen that value should range somewhere between 1.5 and 2.0, but

**Comment by Kerollmops** [comment]
Yup, it's indeed equal to 2.0 but I send you this screenshot that show that the egui blueprint part of the screen is not at scale.

<img width="1680" alt="Capture d’écran 2022-01-30 à 17 40 00" src="https://user-images.githubusercontent.com/3610253/151708598-f1dac919-ef64-400f-a7f8-b644ab130504.png">

**Comment by setzer22** [comment]
Ah! I see the issue now. The bottom part of the Ui is what's wrong. To support zooming for the node editor, I have to ignore the window scaling (because the panel gets its own dpi-independent scale from zoom). But I should compensate that by setting the default zoom to the right value, right now it's hard-coded at `1.0`.

That's an easy fix, I'll push an update shortly addressing this :+1:

**Comment by setzer22** [comment]
Fixed in f957a44
